# Generated by Django 5.1.1 on 2024-10-07 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_orderdetail_stripe_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='stripe_session_id',
        ),
    ]
